pathParameters = parameters.txt
pathOUT = /tmp/structsim-results
pathSimulator = /tmp/structsim-simulator
pathToSimulatorResultFile = /tmp/structsim-simulator/results/results.txt
cuttOfPlanning = 3
typeCuttOfPlanning = INT
